# See config options https://book.getfoundry.sh/reference/config.html

[profile.default]
solc = "0.8.21"
src = 'contracts'
out = 'forge-out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'

